- id: pre-commit-generate-manifests
  name: Generate Configmap Manifests
  entry: manifests/generate-manifests.sh
  language: script
  description: Generates ConfigMap manifests from source files
  always_run: true
  stages: [commit-msg]
- id: pre-commit-generate-alert-rulesets
  name: Generate Alert Rulesets
  entry: alerts/generate-rulesets.sh
  language: script
  description: Generates AlertManager manifests from source files
  always_run: true
  stages: [commit-msg]
