- id: pre-commit-generate-manifests
  name: Generate Configmap Manifests
  entry: manifests/generate-manifests.sh
  language: script
  description: Generates ConfigMap manifests from source files
  always_run: true
  stages: [commit-msg]
