---
ignore: |
  *.sops.*
extends: default
rules:
  truthy:
    allowed-values: ["true", "false"]
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  comments-indentation: {}
  line-length: disable
  braces:
    forbid: true
  brackets:
    forbid: true
  indentation:
    spaces: 2
  quoted-strings:
    quote-type: double
    required: only-when-needed
